config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :microposts do
    resources :comments
    get '/restore', to: 'microposts#restore'
    get '/destroy', to: 'microposts#destroy_post'
  end

  resources :users do
   get '/recyclebin', to: 'users#recycle_bin'
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new
  if current_user == nil
    redirect_to login_url
  else
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.new(parent_id: params[:parent_id])
    @parent_id = @comment.parent_id
  end
end

def create
  if current_user == nil
    redirect_to login_url
  else
    @micropost = Micropost.find(params[:micropost_id])
    Comment.create!(comment: params[:comment][:comment], micropost_id: params[:micropost_id], parent_id: params[:comment][:parent_id], user_id: params[:comment][:user_id])
    redirect_to micropost_path(@micropost)
  end
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
<% unless comment.parent_id || !comment.persisted? %>
<p>
 <% comment_owner = User.find(comment.user_id).name%>
 <b><%=comment_owner%> </b>
 <%= comment.comment %>
 <%= link_to 'reply', new_micropost_comment_path(@micropost, parent_id: comment.id), remote: true %>
 <%= render partial: 'comments/reply', locals: {micropost: @micropost, comment:comment}%>
 <%end%>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [@micropost, @micropost.comments.build]) do |f| %>
 <div>
 <%= f.label 'New comment' %>
 <%= f.text_area :comment %>
 </div>
 <div>
<%= f.hidden_field :user_id, value: current_user.id, readonly: true%>
 </div>
 <%= f.submit 'Submit' %>
 <% end %>

app/views/comments/_reply.html.erb
<% if comment.replies.any? %>
 <% comment.replies.each do |reply| %>
 <ul>
<% reply_owner = User.find(reply.user_id).name%>
 <b><%=reply_owner%> </b>
 <%=reply.comment%>
 <%= link_to 'reply', new_micropost_comment_path(@micropost, parent_id: reply.id), remote: true %>
 </ul>
 <ul>
 <%= render partial: 'comments/reply', locals: {micropost: @micropost, comment:reply}%>
 </ul>
 <% end %>
<% end %>
<div id="reply-form-<%= comment.id %>"></div>
  </p>

app/views/comments/new.html.erb
<div>
 <h4> REPLY TO COMMENT </h4>
 <%= form_with(model: [@micropost, @comment]) do |f| %>
 <%= f.hidden_field :parent_id, value: @parent_id %>
 <div>
<%= f.hidden_field :user_id, value: current_user.id, readonly: true%>
 </div>
 <div class="form-group">
 <%= f.label 'Reply' %>
 <%= f.text_area :comment %>
 </div>
 <%= f.submit 'Submit' %>
 <%= link_to 'Cancel', micropost_path(@micropost) %>
 <% end %>
</div>