config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :microposts do
    resources :comments
    get '/restore', to: 'microposts#restore'
    get '/destroy', to: 'microposts#destroy_post'
  end

  resources :users do
   get '/recyclebin', to: 'users#recycle_bin'
  end


end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, uniqueness: true, presence: true, length: { minimum: 6 }

  VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  validates :email , presence: true,uniqueness:{case_sensetive:false}, format:{with:VALID_EMAIL_REGEX,multiline:true}

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Password.create(string, cost: cost)
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]


  def recycle_bin
   begin
    @user = User.find(params[:user_id])
    if current_user != nil && current_user.id == @user.id
      @deleted_micropost = Micropost.where(user_id: params[:user_id], present: 0)
    else
      redirect_to login_url
    end
   rescue ActiveRecord::RecordNotFound => e
    redirect_to '/404'
   end
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    begin
      @user = User.find(params[:id])
      if current_user != nil && current_user.id == @user.id
        render 'show'
      else
        redirect_to login_url
      end
    rescue ActiveRecord::RecordNotFound => e
      redirect_to '/404'
    end
    @microposts = @user.microposts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    if current_user == nil || @user.id != current_user.id
      redirect_to login_url
    end
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @user = User.find(params[:id])
    if current_user == nil || @user.id != current_user.id
      redirect_to login_url
    else
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy

    @user = User.find(params[:id])
    if current_user == nil || @user.id != current_user.id
      redirect_to login_url
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      begin
        @user = User.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to '/404'
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
   <%= form.label :password , style: "display: block" %>
   <%= form.password_field :password %>
  </div>

  <div>
  <%= form.label :password_confirmation, style: "display: block" %>
  <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>id:</strong>
    <%= user.id %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user_path(user.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/recycle_bin.html.erb
<p style="color: red"><%= notice %></p>
<div>
<h2> <%= link_to "Back to User" , user_path(@user) %> </h2>
</div>
<div>
 &nbsp
</div>
<%  @deleted_micropost.each do |m| %>
<div>
<%= image_tag (m.content), :width => "20%"  %>
</div>
<div>
<%= m.id %>
<%= %>
<div>
 <b><%= link_to "restore this micropost" , micropost_restore_path(m) %> </b> <b>/</b>
 <b><%= link_to "delete this post from bin" , micropost_destroy_path(m) %></b>
<%= %>
<div>
 &nbsp
</div>
<div>
 &nbsp
</div>
<div>
 &nbsp
</div>
</div>
<%end%>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<% provide(:title, @user.name) %>
<div>
<%= render @user %>

<%= link_to "recycle-bin", user_recyclebin_path(@user)%>
<div> &nbsp </div>
<%= button_to "Log out", logout_path , method: :delete %>
<%= link_to "create new micropost", new_micropost_path%>
</div>
&nbsp
<div>
  &nbsp
  </div>
<%  @user.microposts.each do |m| %>
<% if m.present == 1 %>
  <div>
    &nbsp
  <%= image_tag (m.content), :width => "20%"  %>
  </div>
  <div>
  <b>press here to see this micropost: </b>
  <%= link_to m.id , micropost_path(m.id)  %>
  </div>
  <div>
  <%= button_to "Destroy this micropost", micropost_path(m.id), method: :delete %>
  <%= link_to "Edit this micropost", edit_micropost_path(m) %>
   </div>
   <div>
  &nbsp
  </div>
  <%end%>
<%end%>
<div>
  &nbsp
  </div>
  <div>
  &nbsp
  </div>
<div>
  <%= link_to "back to microposts", microposts_path %>
  </div>
  <div>
  <%= link_to "Edit this user", edit_user_path(@user) %>
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>